version: "3.1"
services:
  db:
    container_name: seminar-management-db
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seminar-management-db
    ports:
      - '5432:5432'
